name = "juchain-testnet"
rpc_url = "https://testnet-rpc.juchain.org"
chain_id = 202599
hardfork = "cancun"
admin_account = "0x9d50666A60E0573Eb8789Ff7AcadB4666C0A5E7B"
admin_key_source = "env:JUCHAIN_PRIVATE_KEY"
trace_support = true

[gas_policy]
gas_limit = 30000000
max_fee_per_gas = 20000000000
max_priority_fee_per_gas = 1000000007

[namespace_policy]
prefix = "evmtest"
reuse_strategy = "idempotent"

[feature_flags]
base_fee = true
blob = false
prevrandao = false
large_log_payload = false
max_create_child_code = false
create_collision = false
large_nonzero_returndata = false
selfdestruct_created_clears_code = false

[block_context]
rpc_block_tag = "latest"
